### ISSUE TITLE
[dependency] Update halo2 version to latest `main` for the entire workspace

### ISSUE THREAD

**Issue by CPerezz** [appliedzkp/zkevm-circuits#337]
Currently the workspace is using:
```toml
[patch.crates-io]
halo2 = { git = "https://github.com/appliedzkp/halo2.git", rev = "b78c39cacc1c79d287032f1b5f94beb661b3fb42" }
```

The idea is to simply use `main` at latest commit height. So:
```toml
[patch.crates-io]
halo2 = { git = "https://github.com/appliedzkp/halo2.git", rev = "514152c8b83de27a5ce17ef70cc44c4092240bd1" }
```
