### ISSUE TITLE
patch for halo2_proofs not applied correctly in workspace Cargo.toml

### ISSUE THREAD

**Issue by CPerezz** [appliedzkp/zkevm-circuits#373]
After checking some proposals that @kilic had, we realized that the `patch` section in the workspace `Cargo.toml` for `halo2_proofs` is wrongly set.

Current:
```toml
[patch.crates-io]
halo2_proofs = { git = "https://github.com/appliedzkp/halo2.git", tag = "v2022_02_23" }
```

Desired so that we override git deps for other git ones:
```toml
[patch.'https://github.com/appliedzkp/halo2.git']
halo2_proofs = { git = "https://github.com/appliedzkp/halo2.git", tag = "WHATEVER" }
```

This will replace all the `halo2_proofs` deps for the one with the tag specified for all the workspace members that depend on it.

See: https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section
