### ISSUE TITLE
Implement a workflow to automatically select reviewers for PRs

### ISSUE THREAD

**Issue by CPerezz** [appliedzkp/zkevm-circuits#423]
Now that the reviewers group has been created @appliedzkp/zkevm-reviewers .

A workflow will trigger for each PR and select one of the members as designated reviewer for the PR.
Once that happens, the member will select  another contributor to also review the code and provide the two required approvals to merge.

**Comment by CPerezz** [comment]
I wanted to go on the way of GH actions triggering a reivew request with a workflow like: 
```yaml
name: Request review on PRs

# We only run these lints on trial-merges of PRs to reduce noise.
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  request:
    name: Review requester
    runs-on: ubuntu-20.04

    steps:
      - name: Select a reviewer from appliedzkp/zkevm-reviewers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.pull_request.html_url }} \
              --add-reviewer appliedzkp/zkevm-reviewers
```

But as stated in #428 this is not possible yet. So will go for CODEOWNERS which should work no matter what.
